### ISSUE TITLE
Utility functions vs. private or static methods

### ISSUE THREAD

**Issue by tobydriscoll** [complexvariables/conformalmapping#4]
I prefer that functions like plotbox and boundbox be kept out of the main directory. They can be private methods if only one class needs them, or static if they must be shared. If it's meant to be useful for end users, then we can have a @cm class that provides static methods. 

One reason is that the user may already have a 'plotbox' on their path, causing a name clash. It's also not as tidy. :)

**Comment by tobydriscoll** [comment]
I'm going to try using a package called +cm to get this effect. That means that everything outside needs to be referenced with a cm. prefix, or you have to `import cm.*` before working in each session. But it seems like the way forward with namespaces. 

EDIT: Maybe not. It creates a mess where it's impossible to import the names _within_ the package without doing it for every single method.

**Comment by ehkropf** [comment]
I would suggest just using a class named 'cm' with static methods, e.g.,
the plotdefs class.

**Comment by ehkropf** [comment]
I think #8 solves this. Should we rename the class, or does `cmtutil` work? Maybe `cmutil` would be better (why the extra `t` burden)?

**Comment by ehkropf** [comment]
Does #10 sufficiently address this?
