### ISSUE TITLE
Convert SC map classes plots to CMT style

### ISSUE THREAD

**Issue by ehkropf** [complexvariables/conformalmapping#49]
Need to convert
- `diskmap`
- `hplmap`
- `extermap`

We'll try to keep the "animated lines".

**Comment by tobydriscoll** [comment]
This isn't really necessary. Plotting will be handled by the top-level classes for the most part (currently in zgrid). The SC methods can refer to them and add what might be appropriate (e.g., boundaries).

**Comment by ehkropf** [comment]
With the changed plotting scheme, this issue is out of touch.
